### ISSUE TITLE
Installation  errors

### ISSUE THREAD

**Issue by galliroberto** [a2insights/filament-saas-template#45]
When I try to install I got:

- error given by filamentpanel, so I have to comment in services provider
```
  Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.settings' doesn't exist (Connection: mysql, SQL: select `name`, `payload` from `settings` where `group` = features)
```

- wrong migration
```
  2023_12_20_173900_change_status_type_in_schedule_table .............................................................................. 15.84ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 (Connection: mysql, SQL: alter table `schedules` change `new_status` `status` enum('active','inactive','trashed') collate 'utf8mb4_unicode_ci' not null default ''active'')

```

**Comment by a21ns1g4ts** [comment]
To better understand and resolve this problem, please provide your database version

**Comment by galliroberto** [comment]
I found I have to run `php artisan filament-saas:install` before running migration.
Maybe could improve docs in Readme

**Comment by a21ns1g4ts** [comment]
There's a lot of documentation to be done. The basics aren't as solid as they should be yet. I'll review the entire configuration process and improve the documentation, but if you think you can send a temporary solution, I'd appreciate the contribution. I'm aiming to close a stable version soon. For now, I'm not creating update migrations, so you'll need to do updates manually at some point. Even so, I can use it in production safely. I've already been able to test and verify the most sensitive security issues.

**Comment by galliroberto** [comment]
I'm just trying now.
Everything I discover I write down,I want to help you.

git clone
composer install
artisan key:generate
artisan filament-saas:install

and now
![image](https://github.com/user-attachments/assets/6d8b2d31-016c-495e-85f9-4ee47332bf5a)

in settings table missing 2 params

- og
- sitemap

![image](https://github.com/user-attachments/assets/d7b2d276-fabf-4331-9d1d-19b8d9ddea15)

now it works
![image](https://github.com/user-attachments/assets/516f0f36-d0f9-4210-a229-9074bb04af9f)

**Comment by a21ns1g4ts** [comment]
#[ab40768](https://github.com/a2insights/filament-saas-template/commit/ab4076812ab6db98bd61d0bc2df3798a612e8239)
